services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - supabase
    networks:
      - shortie-nework

  supabase:
    image: supabase/postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - shortie-nework

networks:
  shortie-nework:
    driver: bridge